# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20170407_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
