# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20170407_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DateTime',
        ),
        migrations.AddField(
            model_name='app',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Date'),
        ),
        migrations.AddField(
            model_name='app',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Time'),
        ),
    ]
